# Formative Assignment

**Deadline, Thursday 3rd March 6 PM GMT**

There are 5 exercises in these assignment. Each completed exercise is awarded 4 points for a total of 20 points. In order to pass the final assigment you will need to reach at least 40 points out of 100.

Please send me your solutions either via email (massimiliano.izzo@conted.ox.ac.uk) or via slack. Send me the notebook with your name appended to the file name.

In [1]:
## Let's import the libraries we are going to use later on
import numpy as np
import pandas as pd

# Let's set the precision for NumPy and Pandas
np.set_printoptions(precision=3)
pd.options.display.float_format = '{:,.2f}'.format

## Exercises on Data Structures

### 1. Compute statistics on a Python list [4 points]
Given the following list
```
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]
```
Compute the mean, the median and the standard deviation of the values in the list, using only built-in functionalities of python (no imported libraries, no NumPy or Pandas)

In [22]:
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]

# Write your solution here
l.sort()

total_l = sum(l)
length_l = len(l)
mean_l = total_l/length_l

med_index = length_l/2

median_index1 = med_index.__ceil__()
median_index2 = med_index.__floor__()

median_l = (l[median_index1] + l[median_index2])/2

sum_sqdiff=0
for x in l:
    sum_sqdiff += (x - mean_l)**2

stndev_l = ((sum_sqdiff)/length_l)**(0.5)

print("Mean of l is",mean_l)
print("Median of l is",median_l)
print("Standard deviaition of l is",stndev_l)


Mean of l is 99.6923076923077
Median of l is 14.5
Standard deviaition of l is 260.6044407837537


### 2. Create a dictionary from a list of tuples (records) [4 points]

Given the following list of tuples, each one holding a record
```
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
```
Convert them into a list of dictionaries, using the first tuple as keys for all the dictionaries and all the other tuples as values, one per dictionary. 
Expected result:

```
books = [{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]
```

In [32]:
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]

## Write your solution here

dict_labs = records[0]
data_stuff = records[1:]

books=[]

for el in data_stuff:
    item = dict(zip(dict_labs,el))
    books.append(item)
print(books)


[{'author': 'J. R. R. Tolkien', 'title': 'The Fellowship of the Ring', 'publication_year': 1954, 'page_count': 398}, {'author': 'J. K. Rowling', 'title': "Harry Potter and the Philosopher's stone", 'publication_year': 1996, 'page_count': 223}, {'author': 'Evelyn Waugh', 'title': 'Brideshead Revisited', 'publication_year': 1945, 'page_count': 402}, {'author': 'Philip K. Dick', 'title': 'Ubik', 'publication_year': 1969, 'page_count': 202}, {'author': 'Thomas Pynchon', 'title': "Gravity's Rainbow", 'publication_year': 1973, 'page_count': 760}, {'author': 'Stephen King', 'title': 'The Stand', 'publication_year': 1978, 'page_count': 829}]


## Exercises on Numpy

For these exercises we will work on the IRIS dataset, a very popular multivariate dataset for data anaylisis, first introduced by Ronald Fisher in 1936.

See more about the IRIS dataset heare: https://archive.ics.uci.edu/ml/datasets/Iris

The data source is the file `iris.data` retrieved from the Web. It contains the data for this example in comma separated values (CSV) format. The number of columns is 5 and the number of rows is 150. The data set is composed of 50 samples from each of three species of Iris Flower: Iris Setosa, Iris Virginica and Iris Versicolor. Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species one from each other.

The variables are:

    sepal_length: Sepal length, in centimeters.
    sepal_width: Sepal width, in centimeters.
    petal_length: Petal length, in centimeters.
    petal_width: Petal width, in centimeters.

The three categories of Irises are: 'Iris Setosa', 'Iris Versicolor', and 'Iris Virginica'. 

Let's first import the `iris` dataset as a 1-dimensional array of tuples.

In [33]:
# Input:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', 
                     names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
                     dtype=[np.float, np.float, np.float, np.float, '|S15']
)

<ipython-input-33-617228730f9c>:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=[np.float, np.float, np.float, np.float, '|S15']


In [34]:
iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

### 3A. How to convert a 1d array of tuples to a 2d numpy array [2 points]

Exercise: convert the `iris` 1D array to a numeric-only 2D array `iris_data` by omitting the species text field. Create a `iris_label` 1D array containing only the species text field. Keep the same indexing/order as in the original array.

In [38]:
## Write your solution here
iris_data = np.array([list(row)[0:4] for row in iris])
iris_labels = np.array([list(row)[4] for row in iris])
print(iris_data[:4])
print(iris_labels[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa']


### 3B. Split the IRIS dataset by Label [2 points]


Split the dataset in `iris_data` according to the labels `iris_labels`. 

In [39]:
# Write your solution here
iris_by_label = {
    label: iris_data[iris_labels == label] for label in set(iris_labels)
}
print(iris_by_label)


{b'Iris-virginica': array([[6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 

### 4. Compute statistics with Numpy [4 points]

1) For each flower species compute the key statistics for `sepal width`:
- mean
- median
- standard deviation

Answer the following questions:

    a) Which is the flower type with the largest mean value for `sepal_width`?
    b) Which is the flower type with the smallest median value for `sepal_width`?
    
2) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?

In [60]:
### Compute mean, median, and standard deviation for `sepal width` here:
statistics = {}
for species, dataset in iris_by_label.items():
    statistics[species] = {
        'mean': np.mean(dataset[1], axis=0),
        'median': np.median(dataset[1], axis=0),
        'std': np.std(dataset[1], axis=0)        
}
print(statistics)

big_mean = max(d['mean'] for d in statistics.values())
small_median = min(d['median'] for d in statistics.values())

for name, stats in statistics.items():
    if stats['mean']==big_mean:
        print(name,"has largest mean")
    if stats['median']==small_median:
        print(name,"has smallest median")

{b'Iris-virginica': {'mean': 3.875, 'median': 3.9, 'std': 1.6192204914711275}, b'Iris-versicolor': {'mean': 3.9000000000000004, 'median': 3.85, 'std': 1.7930421077041108}, b'Iris-setosa': {'mean': 2.375, 'median': 2.2, 'std': 1.7640507362318127}}
b'Iris-versicolor' has largest mean
b'Iris-setosa' has smallest median


In [66]:
### Compute the correlation coefficients here
correlations = {}

for species, dataset in iris_by_label.items():
    correlations[species]={
        'corr': np.corrcoef(dataset[1], dataset[2])
}

print(correlations)

high_corr = max(d['corr'][0][1] for d in correlations.values())

for name, corr in correlations.items():
    if corr['corr'][0][1] ==high_corr:
        print(name,"has highest correlation between width and length")

{b'Iris-virginica': {'corr': array([[1.   , 0.998],
       [0.998, 1.   ]])}, b'Iris-versicolor': {'corr': array([[1.   , 0.998],
       [0.998, 1.   ]])}, b'Iris-setosa': {'corr': array([[1.   , 0.997],
       [0.997, 1.   ]])}}
b'Iris-virginica' has highest correlation between width and length


### 5. How to create a new column from existing columns of a numpy array [4 points]

Create a new column for the flower volume V in `iris`, where volume is computing according to this formula (the assumption here is that the shape of the iris flower is approximately conical):

$$ Volume = \frac{\pi \times Sepal Length^2 \times Petal Length}{3}$$

In [105]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3], skip_header=True)


# Write your solution here
volume = (np.pi*(iris_2d[:,0]**2)*iris_2d[:,2])/3
volume=volume[:,np.newaxis]

data = np.hstack((iris_2d, volume))
data

array([[4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01, 3.520e+01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01, 3.007e+01],
       [4.600e+00, 3.100e+00, 1.500e+00, 2.000e-01, 3.324e+01],
       [5.000e+00, 3.600e+00, 1.400e+00, 2.000e-01, 3.665e+01],
       [5.400e+00, 3.900e+00, 1.700e+00, 4.000e-01, 5.191e+01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01, 3.102e+01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01, 3.927e+01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01, 2.838e+01],
       [4.900e+00, 3.100e+00, 1.500e+00, 1.000e-01, 3.771e+01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01, 4.580e+01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01, 3.860e+01],
       [4.800e+00, 3.000e+00, 1.400e+00, 1.000e-01, 3.378e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01, 2.130e+01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01, 4.227e+01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01, 5.104e+01],
       [5.400e+00, 3.900e+00, 1.300e+00,